//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 11:41:37 AM CET 
//


package com.liconic.binding.regeneron;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.liconic.binding.regeneron package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PlatePlateBarcode_QNAME = new QName("http://regeneron.liconic.com", "PlateBarcode");
    private final static QName _CommandReceiver_QNAME = new QName("http://regeneron.liconic.com", "Receiver");
    private final static QName _CommandDate_QNAME = new QName("http://regeneron.liconic.com", "Date");
    private final static QName _CommandUser_QNAME = new QName("http://regeneron.liconic.com", "User");
    private final static QName _CommandStatus_QNAME = new QName("http://regeneron.liconic.com", "Status");
    private final static QName _CommandCancelledBy_QNAME = new QName("http://regeneron.liconic.com", "CancelledBy");
    private final static QName _STXRequestExceptions_QNAME = new QName("http://regeneron.liconic.com", "Exceptions");
    private final static QName _STXRequestPlates_QNAME = new QName("http://regeneron.liconic.com", "Plates");
    private final static QName _STXRequestResponse_QNAME = new QName("http://regeneron.liconic.com", "Response");
    private final static QName _TubePX_QNAME = new QName("http://regeneron.liconic.com", "PX");
    private final static QName _TubePY_QNAME = new QName("http://regeneron.liconic.com", "PY");
    private final static QName _TubeVolume_QNAME = new QName("http://regeneron.liconic.com", "Volume");
    private final static QName _ExceptionErrBarcode_QNAME = new QName("http://regeneron.liconic.com", "ErrBarcode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.liconic.binding.regeneron
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link STXRequest }
     * 
     */
    public STXRequest createSTXRequest() {
        return new STXRequest();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link Plates }
     * 
     */
    public Plates createPlates() {
        return new Plates();
    }

    /**
     * Create an instance of {@link Exceptions }
     * 
     */
    public Exceptions createExceptions() {
        return new Exceptions();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Tube }
     * 
     */
    public Tube createTube() {
        return new Tube();
    }

    /**
     * Create an instance of {@link Tubes }
     * 
     */
    public Tubes createTubes() {
        return new Tubes();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link Plate }
     * 
     */
    public Plate createPlate() {
        return new Plate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "PlateBarcode", scope = Plate.class)
    public JAXBElement<String> createPlatePlateBarcode(String value) {
        return new JAXBElement<String>(_PlatePlateBarcode_QNAME, String.class, Plate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "Receiver", scope = Command.class)
    public JAXBElement<String> createCommandReceiver(String value) {
        return new JAXBElement<String>(_CommandReceiver_QNAME, String.class, Command.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "Date", scope = Command.class)
    public JAXBElement<XMLGregorianCalendar> createCommandDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CommandDate_QNAME, XMLGregorianCalendar.class, Command.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "User", scope = Command.class)
    public JAXBElement<String> createCommandUser(String value) {
        return new JAXBElement<String>(_CommandUser_QNAME, String.class, Command.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "Status", scope = Command.class)
    public JAXBElement<String> createCommandStatus(String value) {
        return new JAXBElement<String>(_CommandStatus_QNAME, String.class, Command.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "CancelledBy", scope = Command.class)
    public JAXBElement<String> createCommandCancelledBy(String value) {
        return new JAXBElement<String>(_CommandCancelledBy_QNAME, String.class, Command.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exceptions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "Exceptions", scope = STXRequest.class)
    public JAXBElement<Exceptions> createSTXRequestExceptions(Exceptions value) {
        return new JAXBElement<Exceptions>(_STXRequestExceptions_QNAME, Exceptions.class, STXRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Plates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "Plates", scope = STXRequest.class)
    public JAXBElement<Plates> createSTXRequestPlates(Plates value) {
        return new JAXBElement<Plates>(_STXRequestPlates_QNAME, Plates.class, STXRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "Response", scope = STXRequest.class)
    public JAXBElement<Response> createSTXRequestResponse(Response value) {
        return new JAXBElement<Response>(_STXRequestResponse_QNAME, Response.class, STXRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "PX", scope = Tube.class)
    public JAXBElement<Byte> createTubePX(Byte value) {
        return new JAXBElement<Byte>(_TubePX_QNAME, Byte.class, Tube.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "PY", scope = Tube.class)
    public JAXBElement<String> createTubePY(String value) {
        return new JAXBElement<String>(_TubePY_QNAME, String.class, Tube.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "Volume", scope = Tube.class)
    public JAXBElement<Float> createTubeVolume(Float value) {
        return new JAXBElement<Float>(_TubeVolume_QNAME, Float.class, Tube.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://regeneron.liconic.com", name = "ErrBarcode", scope = Exception.class)
    public JAXBElement<String> createExceptionErrBarcode(String value) {
        return new JAXBElement<String>(_ExceptionErrBarcode_QNAME, String.class, Exception.class, value);
    }

}
