//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 11:41:37 AM CET 
//


package com.liconic.binding.regeneron;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Plate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Plate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PlateOrder" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PlateBarcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tubes" type="{http://regeneron.liconic.com}Tubes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plate", propOrder = {
    "plateOrder",
    "plateBarcode",
    "tubes"
})
public class Plate {

    @XmlElement(name = "PlateOrder")
    protected int plateOrder;
    @XmlElementRef(name = "PlateBarcode", namespace = "http://regeneron.liconic.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> plateBarcode;
    @XmlElement(name = "Tubes", required = true)
    protected Tubes tubes;

    /**
     * Gets the value of the plateOrder property.
     * 
     */
    public int getPlateOrder() {
        return plateOrder;
    }

    /**
     * Sets the value of the plateOrder property.
     * 
     */
    public void setPlateOrder(int value) {
        this.plateOrder = value;
    }

    /**
     * Gets the value of the plateBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPlateBarcode() {
        return plateBarcode;
    }

    /**
     * Sets the value of the plateBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPlateBarcode(JAXBElement<String> value) {
        this.plateBarcode = value;
    }

    /**
     * Gets the value of the tubes property.
     * 
     * @return
     *     possible object is
     *     {@link Tubes }
     *     
     */
    public Tubes getTubes() {
        return tubes;
    }

    /**
     * Sets the value of the tubes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tubes }
     *     
     */
    public void setTubes(Tubes value) {
        this.tubes = value;
    }

}
