//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 11:41:37 AM CET 
//


package com.liconic.binding.regeneron;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Command" type="{http://regeneron.liconic.com}Command"/>
 *         &lt;element name="Plates" type="{http://regeneron.liconic.com}Plates" minOccurs="0"/>
 *         &lt;element name="Exceptions" type="{http://regeneron.liconic.com}Exceptions" minOccurs="0"/>
 *         &lt;element name="Response" type="{http://regeneron.liconic.com}Response" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "command",
    "plates",
    "exceptions",
    "response"
})
@XmlRootElement(name = "STXRequest")
public class STXRequest {

    @XmlElement(name = "Command", required = true)
    protected Command command;
    @XmlElementRef(name = "Plates", namespace = "http://regeneron.liconic.com", type = JAXBElement.class, required = false)
    protected JAXBElement<Plates> plates;
    @XmlElementRef(name = "Exceptions", namespace = "http://regeneron.liconic.com", type = JAXBElement.class, required = false)
    protected JAXBElement<Exceptions> exceptions;
    @XmlElementRef(name = "Response", namespace = "http://regeneron.liconic.com", type = JAXBElement.class, required = false)
    protected JAXBElement<Response> response;

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link Command }
     *     
     */
    public Command getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link Command }
     *     
     */
    public void setCommand(Command value) {
        this.command = value;
    }

    /**
     * Gets the value of the plates property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Plates }{@code >}
     *     
     */
    public JAXBElement<Plates> getPlates() {
        return plates;
    }

    /**
     * Sets the value of the plates property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Plates }{@code >}
     *     
     */
    public void setPlates(JAXBElement<Plates> value) {
        this.plates = value;
    }

    /**
     * Gets the value of the exceptions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Exceptions }{@code >}
     *     
     */
    public JAXBElement<Exceptions> getExceptions() {
        return exceptions;
    }

    /**
     * Sets the value of the exceptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Exceptions }{@code >}
     *     
     */
    public void setExceptions(JAXBElement<Exceptions> value) {
        this.exceptions = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Response }{@code >}
     *     
     */
    public JAXBElement<Response> getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Response }{@code >}
     *     
     */
    public void setResponse(JAXBElement<Response> value) {
        this.response = value;
    }

}
